### PR TITLE
Fix payload terminology

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

- align terminology with RFC7231 term. 

## Note

I'd consider switching to httpbis-semantics https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#payload

### CODE REVIEW

**Comment by ioggstream** [comment]
Hi @dickhardt @aaronpk it would be great to have some feedback on this PR. In case I could brush even more the spec to ensure compatibility with the ongoing HTTP work :)

**Comment by aaronpk** [comment]
Thanks! I'm working on this this week so I will take a look soon!

**Comment by ioggstream** [comment]
@aaronpk let me know if you need more feedback ;)

**Comment by aaronpk** [comment]
This looks great. I'm not sure of the other implications of switching the references to draft-ietf-httpbis-semantics so we can discuss that in a new issue if you'd like.

**Pull request merged**
